# Generated by Django 4.2.4 on 2023-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_trainerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='specialization',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
