# Generated by Django 4.2.4 on 2023-08-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_trainerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
