# Generated by Django 4.2.4 on 2023-08-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_trainerprofile_specialization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerProfile',
            new_name='TrainersProfile',
        ),
    ]
