# Generated by Django 4.2.4 on 2023-08-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_trainerprofile_trainersprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainersProfile',
            new_name='FitnessTrainerProfile',
        ),
    ]
