# Generated by Django 4.2.4 on 2023-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_trainersprofile_fitnesstrainerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstrainerprofile',
            name='experience',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
