# Generated by Django 4.2.4 on 2023-08-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_fitnesstrainerprofile_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnesstrainerprofile',
            old_name='experience',
            new_name='trainer_experience',
        ),
    ]
