# Generated by Django 4.2.4 on 2023-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_trainer_experience_fitnesstrainerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstrainerprofile',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
    ]
