# Generated by Django 4.2.4 on 2023-09-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_nutritionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nutrition_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.nutritionplan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workout_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.workoutplan'),
        ),
    ]
